#!/bin/bash

echo "======================================"
echo "📦 Supabase Setup Guide"
echo "======================================"
echo ""
echo "This guide will help you set up Supabase for your InnoSpot app"
echo ""
echo "STEP 1: Create Supabase Project"
echo "--------------------------------"
echo "1. Go to: https://supabase.com"
echo "2. Sign in/Sign up"
echo "3. Click 'New Project'"
echo "4. Enter:"
echo "   - Project name: appinnospot"
echo "   - Database password: (save this!)"
echo "   - Region: (choose closest to you)"
echo "5. Click 'Create new project'"
echo ""
echo "STEP 2: Get Your Credentials"
echo "--------------------------------"
echo "In your Supabase project:"
echo "1. Go to Settings → API"
echo "2. Copy these values:"
echo "   - Project URL (https://xxxxx.supabase.co)"
echo "   - anon/public key (eyJ...)"
echo ""
echo "STEP 3: Add to Vercel"
echo "--------------------------------"
echo "1. Go to: https://vercel.com/dashboard"
echo "2. Select your project"
echo "3. Go to Settings → Environment Variables"
echo "4. Add:"
echo "   VITE_SUPABASE_URL = [your-project-url]"
echo "   VITE_SUPABASE_ANON_KEY = [your-anon-key]"
echo "5. Check all environments (Production, Preview, Development)"
echo ""
echo "STEP 4: Run Database Migrations"
echo "--------------------------------"
echo "In Supabase SQL Editor, run migrations in this order:"
echo ""
echo "Critical migrations (run these first):"
echo "  1. 020_core_authentication.sql"
echo "  2. 021_projects_and_spaces.sql"
echo "  3. 022_knowledge_and_content.sql"
echo "  4. 023_studio_assets.sql"
echo "  5. 024_capabilities_and_marketplace.sql"
echo "  6. 025_row_level_security.sql"
echo "  7. 026_performance_optimization.sql"
echo "  8. 027_critical_security_fixes.sql"
echo ""
echo "Then run the others if needed:"
echo "  - 010_create_demo_user.sql (for demo accounts)"
echo "  - 011_user_settings_comprehensive.sql"
echo "  - Other numbered files as needed"
echo ""
echo "STEP 5: Redeploy on Vercel"
echo "--------------------------------"
echo "1. Go to Vercel dashboard"
echo "2. Click Deployments tab"
echo "3. Redeploy latest deployment"
echo ""
echo "======================================"
echo "🎯 Quick Links:"
echo "======================================"
echo "Supabase: https://supabase.com/dashboard"
echo "Vercel: https://vercel.com/dashboard"
echo "Your App: https://appinnospot.vercel.app"
echo ""
echo "Need the migration files?"
echo "They're in: ./supabase/migrations/"
echo ""